### ISSUE TITLE
Sanitize missing PROJECT_ID

### ISSUE THREAD

**Issue by mmahut** [blockfrost/blockfrost-demo-asset-explorer#1]
Let's make sure `PROJECT_ID` is defined and that it is working. If not, show a banner in the explorer asking people to create and defined one.

**Comment by vladimirvolek** [comment]
https://github.com/blockfrost/blockfrost-demo-asset-explorer/commit/0d936860e9a6622f9ff686ad05ee10ef5a3785d8
